import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SecurityBlocker from "@/components/securityBlocker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ajeet Sharma - Portfolio",
  description: "Generated by Ajeet Sharma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <link
          href="https://fonts.googleapis.com/css2?family=McLaren&display=swap"
          rel="stylesheet"
          precedence="default"
        />
        <link rel="icon" href="/icon.png" type="image/png" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mclaren-font bg-[#11071F]`}
      >
        <SecurityBlocker />
        {children}
      </body>
    </html>
  );
}
